name: Create Env

description: Create .env file based on env type

inputs:
  environment:
    description: "test/production input"
    required: true

runs:
  using: composite

  steps:
    - name: create test .env
      if: inputs.environment == 'test'
      run: echo "create test env"
      shell: bash
    - name: create production .env
      if: inputs.environment == 'production'
      run: echo "create production env"
      shell: bash
