name: Create env

description: Create env file

inputs:
  directory:
    required: false
  file-name:
    required: true
  APP_HOST:
    required: true
  APP_PORT:
    required: true
  FRONTEND_HOST:
    required: true
  DB_URL:
    required: true
  SECRET_JWT:
    required: true
  CONSIGLIORE_PASSWORD:
    required: true
  CAPOREGIME_PASSWORD:
    required: true
  SOLDATO_PASSWORD:
    required: true

runs:
  using: composite

  steps:
    - name: create file
      run: |
        mkdir -p ${{ inputs.directory }}
        cd ${{ inputs.directory}}
        echo 'APP_HOST="${{ inputs.APP_HOST }}"' > ${{ inputs.file-name }}
        echo 'APP_PORT=${{ inputs.APP_PORT }}' >> ${{ inputs.file-name }}
        echo 'FRONTEND_HOST="${{ inputs.FRONTEND_HOST }}"' >> ${{ inputs.file-name }}
        echo 'DB_URL="${{ inputs.DB_URL }}"' >> ${{ inputs.file-name }}
        echo 'SECRET_JWT="${{ inputs.SECRET_JWT }}"' >> ${{ inputs.file-name }}
        echo 'CONSIGLIORE_PASSWORD="${{ inputs.CONSIGLIORE_PASSWORD }}"' >> ${{ inputs.file-name }}
        echo 'CAPOREGIME_PASSWORD="${{ inputs.CAPOREGIME_PASSWORD }}"' >> ${{ inputs.file-name }}
        echo 'SOLDATO_PASSWORD="${{ inputs.SOLDATO_PASSWORD }}"' >> ${{ inputs.file-name }}
      shell: bash
