name: Create users

inputs:
  username:
    required: true
  server:
    required: true
  ssh-key:
    required: true
  server-dir:
    description: "must end with trailing slash / and must exist"
    required: false
    default: ~/

runs:
  using: composite

  steps:
    - name: create users
      run: |
        echo "${{ inputs.ssh-key }}" > ~/.ssh.private-key
        chmod 600 ~/.ssh.private-key
        ssh -T -o StrictHostKeyChecking=no -i ~/.ssh.private-key ${{ inputs.username }}@${{ inputs.server }} << EOL
        cd ${{ inputs.server-dir}}
        ~/bin/node ./db/tools/createDb/createUsersDb.js
        EOL
      shell: bash
