### these tests use https://marketplace.visualstudio.com/items?itemName=humao.rest-client vscode plugin

### Token variable
@token = {{login.response.headers.Authorization}}
@userId = {{users.response.body.data.users[2].id}}
@enemyId = {{enemies.response.body.data.enemies[0].id}}
@keyGiverId = {{keyGivers.response.body.data.keyGivers[0].id}}

### Auth Api
### Login - Soldato
# @name login
POST http://localhost:3001/api/auth/login
content-type: application/json

{
    "role": "Soldato",
    "password": "test1234"
}

### Login - Caporegime
# @name login
POST http://localhost:3001/api/auth/login
content-type: application/json

{
    "role": "Caporegime",
    "password": "test1234"
}

### Login - Consigliore
# @name login
POST http://localhost:3001/api/auth/login
content-type: application/json

{
    "role": "Consigliore",
    "password": "test1234"
}

### Login - wrong role
# @name login
POST http://localhost:3001/api/auth/login
content-type: application/json

{
    "role": "Soldatos",
    "password": "test1234"
}

### Login - wrong password
# @name login
POST http://localhost:3001/api/auth/login
content-type: application/json

{
    "role": "Soldato",
    "password": "test1234x"
}

### Logout
# @name login
GET http://localhost:3001/api/auth/logout
Authorization: {{token}}

### Users Api
### get all users
# @name users
GET http://localhost:3001/api/users
Authorization: {{token}}

### change password (of Soldato)
PATCH http://localhost:3001/api/users/{{userId}}
Authorization: {{token}}
content-type: application/json

{
    "password": "test1234"
}

### change password (of Soldato) - too short
PATCH http://localhost:3001/api/users/{{userId}}
Authorization: {{token}}
content-type: application/json

{
    "password": "test"
}

### change password (of Soldato) - not provided
PATCH http://localhost:3001/api/users/{{userId}}
Authorization: {{token}}
content-type: application/json

{
    "password": ""
}

### Enemies Api
### get all enemies
# @name enemies
GET http://localhost:3001/api/enemies
Authorization: {{token}}

### add enemy
POST http://localhost:3001/api/enemies
Authorization: {{token}}
content-type: application/json

{
    "name": "test"
}

### delete enemy
DELETE http://localhost:3001/api/enemies/{{enemyId}}
Authorization: {{token}}

### keyGivers Api
### get all keyGivers
# @name keyGivers
GET http://localhost:3001/api/keygivers
Authorization: {{token}}

### add new keyGiver
POST http://localhost:3001/api/keygivers
Authorization: {{token}}
content-type: application/json

{
    "name": "kluczek",
    "respawnTime": 0
}

### update keyGiver
PATCH http://localhost:3001/api/keygivers/{{keyGiverId}}
Authorization: {{token}}
content-type: application/json

{
    "name": "klucz",
    "respawnTime": 24,
    "description": "Some description"
}

### delete keyGiver
DELETE http://localhost:3001/api/keygivers/{{keyGiverId}}
Authorization: {{token}}

### add new timestamp
PATCH http://localhost:3001/api/keygivers/addtimestamp/{{keyGiverId}}
Authorization: {{token}}
content-type: application/json

{
    "date": "Tue, 12 Apr 2022 22:00:00 GMT",
    "wasEmpty": true
}