### these tests use https://marketplace.visualstudio.com/items?itemName=humao.rest-client vscode plugin

### Global variables
@token = {{login.response.body.data.token}}
@enemyId = {{enemies.response.body.data.enemies[0].id}}

### Auth Api
### Login - Soldato
# @name login
POST {{url}}/api/auth/login
content-type: application/json

{
    "role": "Soldato",
    "password": "test1234"
}

### Login - Caporegime
# @name login
POST {{url}}/api/auth/login
content-type: application/json

{
    "role": "Caporegime",
    "password": "test1234"
}

### Login - Consigliore
# @name login
POST {{url}}/api/auth/login
content-type: application/json

{
    "role": "Consigliore",
    "password": "test1234"
}

### Logout
# @name login
GET {{url}}/api/auth/logout
Authorization: Bearer {{token}}

### Enemies Api
### get all enemies
# @name enemies
GET {{url}}/api/enemies
Authorization: Bearer {{token}}

### add enemy
POST {{url}}/api/enemies
Authorization: Bearer {{token}}
content-type: application/json

{
    "name": "bilbo"
}

### delete enemy
DELETE {{url}}/api/enemies/{{enemyId}}
Authorization: Bearer {{token}}

### update enemy
PATCH {{url}}/api/enemies/{{enemyId}}
Authorization: Bearer {{token}}
content-type: application/json

{
    "name": "Bilbo",
    "guild": "wks"
}
