### these tests use https://marketplace.visualstudio.com/items?itemName=humao.rest-client vscode plugin

### Token variable
@token = {{login.response.headers.Authorization}}
@keyGiverId = {{keyGivers.response.body.data.keyGivers[0].id}}

### Auth Api
### Login - Soldato
# @name login
POST http://localhost:3001/api/auth/login
content-type: application/json

{
    "role": "Soldato",
    "password": "test1234"
}

### Login - Caporegime
# @name login
POST http://localhost:3001/api/auth/login
content-type: application/json

{
    "role": "Caporegime",
    "password": "test1234"
}

### Login - Consigliore
# @name login
POST http://localhost:3001/api/auth/login
content-type: application/json

{
    "role": "Consigliore",
    "password": "test1234"
}

### Logout
# @name login
GET http://localhost:3001/api/auth/logout
Authorization: {{token}}

### keyGivers Api
### get all keyGivers
# @name keyGivers
GET http://localhost:3001/api/keygivers
Authorization: {{token}}

### get keyGiver details
GET http://localhost:3001/api/keygivers/{{keyGiverId}}
Authorization: {{token}}

### get keyGiver details - bad id
GET http://localhost:3001/api/keygivers/6345d568ae474b461be9581c
Authorization: {{token}}

### add new keyGiver
POST http://localhost:3001/api/keygivers
Authorization: {{token}}
content-type: application/json

{
    "name": "kluczek1",
    "respawnTime": 20
}

### update keyGiver
PATCH http://localhost:3001/api/keygivers/{{keyGiverId}}
Authorization: {{token}}
content-type: application/json

{
    "name": "kluczek3",
    "respawnTime": 24,
    "description": "Some description2"
}

### delete keyGiver
DELETE http://localhost:3001/api/keygivers/{{keyGiverId}}
Authorization: {{token}}

### delete keyGiver - bad id
DELETE http://localhost:3001/api/keygivers/6345d568ae474b
Authorization: {{token}}

### add new timestamp
PATCH http://localhost:3001/api/keygivers/addtimestamp/{{keyGiverId}}
Authorization: {{token}}
content-type: application/json

{
    "date": "Tue, 30 Apr 2022 22:00:00 GMT",
    "wasEmpty": true
}

### add new timestamp - bad date format
PATCH http://localhost:3001/api/keygivers/addtimestamp/{{keyGiverId}}
Authorization: {{token}}
content-type: application/json

{
    "date": "invalid date",
    "wasEmpty": true
}