### these tests use https://marketplace.visualstudio.com/items?itemName=humao.rest-client vscode plugin

### Global variables
@url = http://localhost:3001
@token = {{login.response.body.data.token}}
@keyId = {{keys.response.body.data.keys[0].id}}

### Auth Api
### Login - Soldato
# @name login
POST {{url}}/api/auth/login
content-type: application/json

{
    "role": "Soldato",
    "password": "test1234"
}

### Login - Caporegime
# @name login
POST {{url}}/api/auth/login
content-type: application/json

{
    "role": "Caporegime",
    "password": "test1234"
}

### Login - Consigliore
# @name login
POST {{url}}/api/auth/login
content-type: application/json

{
    "role": "Consigliore",
    "password": "test1234"
}

### Logout
# @name login
GET {{url}}/api/auth/logout
Authorization: {{token}}

### keys Api
### get all keys
# @name keys
GET {{url}}/api/keys
Authorization: {{token}}

### get key details
GET {{url}}/api/keys/{{keyId}}
Authorization: {{token}}

### get key details - bad id
GET {{url}}/api/keys/6345d568ae474b461be9581c
Authorization: {{token}}

### add new key
POST {{url}}/api/keys
Authorization: {{token}}
content-type: application/json

{
    "name": "duzy ciezki klucz25",
    "treasuryName": "Edalbert",
    "domain": "Ishtar"
}

### update key
PATCH {{url}}/api/keys/{{keyId}}
Authorization: {{token}}
content-type: application/json

{
    "name": "duzy ciezki klucz",
    "treasuryName": "Edalbert"
}

### delete key
DELETE {{url}}/api/keys/{{keyId}}
Authorization: {{token}}

### delete key - bad id
DELETE {{url}}/api/keys/6345d568ae474b
Authorization: {{token}}

### add new timestamp
PATCH {{url}}/api/keys/addtimestamp/{{keyId}}
Authorization: {{token}}
content-type: application/json

{
    "date": "Tue, 30 May 2022 23:00:00 GMT",
    "npcName": "Rivannon"
}

### add new timestamp - bad date format
PATCH {{url}}/api/keys/addtimestamp/{{keyId}}
Authorization: {{token}}
content-type: application/json

{
    "date": "invalid date",
    "npcName": true
}