import { ItemArmorClass } from "./ItemArmorClass";
import { ItemTypes } from "./ItemTypes";
import { ItemWeapon } from "./ItemWeapon";
import { ItemWeaponHand } from "./ItemWeaponHand";

export type ConvertedItem = {
  short: string;
  isMagic: boolean;
  type: ItemTypes;
  weaponType: ItemWeapon | null;
  weaponHand: ItemWeaponHand | null;
  weaponSlashingDamage: boolean | null;
  weaponPiercingDamage: boolean | null;
  weaponBluntDamage: boolean | null;
  weaponEffectiveness: number | null;
  weaponBalance: number | null;
  isWeaponSilver: boolean | null;
  armorClass: ItemArmorClass | null;
  armorSlashingRes: number | null;
  armorPiercingRes: number | null;
  armorBluntRes: number | null;
  armorHead: boolean | null;
  armorLeftArm: boolean | null;
  armorRightArm: boolean | null;
  armorChest: boolean | null;
  armorLegs: boolean | null;
  armorFoots: boolean | null;
  armorHands: boolean | null;
  shieldParry: number | null;
  weight: number | null;
  volume: number | null;
  description: string;
};

export type FilteredItem = {
  short: string;
  isMagic: boolean;
  type: ItemTypes;
  weaponType: ItemWeapon | null;
  weaponHand: ItemWeaponHand | null;
  weaponSlashingDamage: boolean | null;
  weaponPiercingDamage: boolean | null;
  weaponBluntDamage: boolean | null;
  weaponEffectiveness: number[] | null;
  weaponBalance: number[] | null;
  isWeaponSilver: boolean | null;
  armorClass: ItemArmorClass | null;
  armorSlashingRes: number[] | null;
  armorPiercingRes: number[] | null;
  armorBluntRes: number[] | null;
  armorHead: boolean | null;
  armorLeftArm: boolean | null;
  armorRightArm: boolean | null;
  armorChest: boolean | null;
  armorLegs: boolean | null;
  armorFoots: boolean | null;
  armorHands: boolean | null;
  shieldParry: number[] | null;
  weight: number | null;
  volume: number | null;
  description: string;
};
