export enum ItemWeaponBalance {
  "wyjatkowo zle",
  "bardzo zle",
  "zle",
  "bardzo kiepsko",
  "kiepsko",
  "przyzwoicie",
  "srednio",
  "niezle",
  "dosc dobrze",
  "dobrze",
  "bardzo dobrze",
  "doskonale",
  "perfekcyjnie",
}
