name: Deploy

description: Build app and deploy via ftp

inputs:
  environment:
    description: "test/production input"
    required: true
  node-version:
    description: "providing node version"
    required: false

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
      if: inputs.node-version != ''
    - name: cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
    - name: build app
      run: |
        less ./config/.env
        node -v
        npm run build
      shell: bash
    - name: send app via ftp
      run: echo "send app via ftp"
      shell: bash
