name: Deploy

description: Build app and deploy via ftp

inputs:
  environment:
    description: test/production
    required: true
    type: string

runs:
  using: composite

    steps:
      - name: get code
        run: echo "get code"
      - name: cache dependencies
        run: echo "cache dependencies"
      - name: install dependencies
        run: echo "install dependencies"
      - name: build app
        run: echo "build app"
      - name: create .env
        uses: ./.github/actions/create-env
        with:
          environment: inputs.environment
      - name: send app via ftp
        run: echo "send app via ftp"
