name: Deploy

description: Build app and deploy via ftp

inputs:
  node-version:
    description: "providing node version"
    required: false
  server:
    required: true
  username:
    required: true
  password:
    required: true
  file:
    description: "must end with trailing slash /"
    required: false
    default: ./
  server-dir:
    description: "must end with trailing slash /"
    required: false
    default:

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
      if: inputs.node-version != ''
    - name: cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
    - name: build app
      run: npm run build
      shell: bash
    - name: archive dist folder
      run: |
        cd dist
        zip -r dist.zip .
        mv dist.zip ../
      shell: bash
    - name: send app via ftp
      run: curl -u ${{ inputs.username }}:${{ inputs.password }} -T ${{ inputs.file }} ftp://${{ inputs.server }}/${{ inputs.server-dir }}
      shell: bash
