name: "[Production] Create Users"

on:
  workflow_dispatch:

jobs:
  create-users:
    runs-on: ubuntu-latest
    env:
      SSH_USERNAME: ${{secrets.SSH_USERNAME_PRODUCTION}}
      SSH_SERVER: ${{secrets.SSH_SERVER_PRODUCTION}}
      SSH_KEY: ${{secrets.SSH_KEY_PRODUCTION}}
      SSH_SERVER_DIR: ${{secrets.SSH_SERVER_DIR_PRODUCTION}}

    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Creating users
        uses: ./.github/actions/create-users
        with:
          username: ${{ env.SSH_USERNAME}}
          server: ${{ env.SSH_SERVER}}
          ssh-key: ${{ env.SSH_KEY}}
          server-dir: ${{ env.SSH_SERVER_DIR}}
