name: "[Test] Create Users"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch reference"
        required: true

jobs:
  create-users:
    runs-on: ubuntu-latest
    env:
      SSH_USERNAME: ${{secrets.SSH_USERNAME_TEST}}
      SSH_SERVER: ${{secrets.SSH_SERVER_TEST}}
      SSH_KEY: ${{secrets.SSH_KEY_TEST}}
      SSH_SERVER_DIR: ${{secrets.SSH_SERVER_DIR_TEST}}

    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Creating users
        uses: ./.github/actions/create-users
        with:
          username: ${{ env.SSH_USERNAME}}
          server: ${{ env.SSH_SERVER}}
          ssh-key: ${{ env.SSH_KEY}}
          server-dir: ${{ env.SSH_SERVER_DIR}}
